version: "3"

services:   
  client:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3000
    networks:
      - server
    
  
  
  nginx:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - client
    networks:
      - server


networks:
  server: