version: "3"

services:   
  client:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    expose:
      - 3000
    networks:
      - server
    
  
  
  nginx:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - client
    networks:
      - server

